import type { ParentDashboardData } from '../types/parent.types';

export const MOCK_PARENT_DASHBOARD: ParentDashboardData = {
  profile: {
    name: 'Mr. Aslam Khan',
    email: 'aslam.khan@email.com',
    phone: '+92 321 5551234',
    avatarInitials: 'AK',
  },
  stats: {
    linkedChildren: 2,
    upcomingSessions: 3,
    avgAttendance: 94,
    overallProgress: 90,
  },
  children: [
    {
      id: 'child-1',
      name: 'Ahmed Aslam',
      grade: 'Class 10',
      board: 'Federal Board',
      avatarInitials: 'AA',
      subjects: ['Physics', 'Mathematics'],
      attendanceRate: 96,
      sessionsThisMonth: 8,
      avgScore: 88,
      linkedAt: '2026-01-15',
    },
    {
      id: 'child-2',
      name: 'Sara Aslam',
      grade: 'Class 8',
      board: 'Federal Board',
      avatarInitials: 'SA',
      subjects: ['English', 'Science'],
      attendanceRate: 91,
      sessionsThisMonth: 6,
      avgScore: 92,
      linkedAt: '2026-03-02',
    },
  ],
  sessions: [
    {
      id: 'sess-1',
      childName: 'Ahmed Aslam',
      tutorName: 'Prof. Ali Ahmed',
      subject: 'Physics',
      date: 'Jul 22, 2026',
      time: '4:00 PM',
      status: 'upcoming',
      amount: 2500,
    },
    {
      id: 'sess-2',
      childName: 'Sara Aslam',
      tutorName: 'Ms. Fatima Noor',
      subject: 'English',
      date: 'Jul 22, 2026',
      time: '6:30 PM',
      status: 'upcoming',
      amount: 2000,
    },
    {
      id: 'sess-3',
      childName: 'Ahmed Aslam',
      tutorName: 'Sara Malik',
      subject: 'Mathematics',
      date: 'Jul 24, 2026',
      time: '5:00 PM',
      status: 'upcoming',
      amount: 2500,
    },
    {
      id: 'sess-4',
      childName: 'Ahmed Aslam',
      tutorName: 'Prof. Ali Ahmed',
      subject: 'Physics',
      date: 'Jul 18, 2026',
      time: '4:00 PM',
      status: 'completed',
      amount: 2500,
    },
    {
      id: 'sess-5',
      childName: 'Sara Aslam',
      tutorName: 'Dr. Hassan Raza',
      subject: 'Science',
      date: 'Jul 16, 2026',
      time: '3:00 PM',
      status: 'completed',
      amount: 2200,
    },
    {
      id: 'sess-6',
      childName: 'Ahmed Aslam',
      tutorName: 'Sara Malik',
      subject: 'Mathematics',
      date: 'Jul 10, 2026',
      time: '5:00 PM',
      status: 'cancelled',
      amount: 2500,
    },
  ],
  notifications: [
    {
      id: 'n1',
      title: 'Session starting soon',
      message: 'Ahmed has Physics with Prof. Ali Ahmed in 1 hour.',
      type: 'session',
      read: false,
      createdAt: '2026-07-22T14:00:00Z',
    },
    {
      id: 'n2',
      title: 'Payment successful',
      message: 'PKR 2,500 paid for Ahmed\'s Mathematics session.',
      type: 'payment',
      read: false,
      createdAt: '2026-07-21T18:30:00Z',
    },
    {
      id: 'n3',
      title: 'Weekly progress report ready',
      message: 'Sara improved 8% in English this week.',
      type: 'progress',
      read: true,
      createdAt: '2026-07-20T09:00:00Z',
    },
    {
      id: 'n4',
      title: 'New tutor message',
      message: 'Prof. Ali Ahmed sent a note about Ahmed\'s homework.',
      type: 'alert',
      read: false,
      createdAt: '2026-07-19T16:45:00Z',
    },
    {
      id: 'n5',
      title: 'Platform update',
      message: 'TutorLink Parent Portal now supports dark mode.',
      type: 'system',
      read: true,
      createdAt: '2026-07-18T10:00:00Z',
    },
    {
      id: 'n6',
      title: 'Session completed',
      message: 'Sara completed Science with Dr. Hassan Raza.',
      type: 'session',
      read: true,
      createdAt: '2026-07-16T15:30:00Z',
    },
  ],
  progress: [
    {
      childId: 'child-1',
      childName: 'Ahmed Aslam',
      subject: 'Mathematics',
      score: 85,
      grade: 'A',
      syllabusCovered: 65,
      trend: 'up',
      trendDelta: 5,
      weeklyBars: [35, 48, 55, 62, 70],
      sessionsCompleted: 10,
      lastUpdated: 'Jul 19, 2026',
    },
    {
      childId: 'child-1',
      childName: 'Ahmed Aslam',
      subject: 'Physics',
      score: 88,
      grade: 'A+',
      syllabusCovered: 72,
      trend: 'up',
      trendDelta: 5,
      weeklyBars: [40, 52, 60, 68, 78],
      sessionsCompleted: 12,
      lastUpdated: 'Jul 20, 2026',
    },
    {
      childId: 'child-2',
      childName: 'Sara Aslam',
      subject: 'English',
      score: 78,
      grade: 'B+',
      syllabusCovered: 58,
      trend: 'down',
      trendDelta: -3,
      weeklyBars: [50, 55, 52, 58, 54],
      sessionsCompleted: 8,
      lastUpdated: 'Jul 20, 2026',
    },
    {
      childId: 'child-2',
      childName: 'Sara Aslam',
      subject: 'Science',
      score: 89,
      grade: 'A',
      syllabusCovered: 70,
      trend: 'up',
      trendDelta: 4,
      weeklyBars: [42, 50, 58, 65, 74],
      sessionsCompleted: 7,
      lastUpdated: 'Jul 18, 2026',
    },
  ],
  weeklyProgress: [
    {
      childId: 'child-1',
      childName: 'Ahmed Aslam',
      avatarInitials: 'AA',
      subject: 'Physics & Math',
      weeks: [
        { label: 'Jun 9', score: 72 },
        { label: 'Jun 16', score: 76 },
        { label: 'Jun 23', score: 79 },
        { label: 'Jun 30', score: 82 },
        { label: 'Jul 7', score: 85 },
        { label: 'Jul 14', score: 88 },
      ],
    },
    {
      childId: 'child-2',
      childName: 'Sara Aslam',
      avatarInitials: 'SA',
      subject: 'English & Science',
      weeks: [
        { label: 'Jun 9', score: 78 },
        { label: 'Jun 16', score: 82 },
        { label: 'Jun 23', score: 85 },
        { label: 'Jun 30', score: 87 },
        { label: 'Jul 7', score: 90 },
        { label: 'Jul 14', score: 92 },
      ],
    },
  ],
  aiRecommendation: {
    summary:
      'Both children are on an upward trajectory. Ahmed is gaining momentum in Physics; Sara shows consistent excellence in English.',
    tips: [
      'Schedule an extra Physics revision session for Ahmed before the waves unit test.',
      'Sara is ready for advanced English comprehension — consider upgrading tutor difficulty.',
      'Maintain 2 sessions per week per subject for best retention through August.',
    ],
    forecasts: [
      {
        week: 'Jul 21 – Jul 27',
        childName: 'Ahmed Aslam',
        projectedScore: 90,
        focus: 'Physics — Electromagnetic waves',
        confidence: 87,
      },
      {
        week: 'Jul 28 – Aug 3',
        childName: 'Ahmed Aslam',
        projectedScore: 92,
        focus: 'Mathematics — Integration basics',
        confidence: 84,
      },
      {
        week: 'Jul 21 – Jul 27',
        childName: 'Sara Aslam',
        projectedScore: 93,
        focus: 'English — Essay writing',
        confidence: 91,
      },
      {
        week: 'Jul 28 – Aug 3',
        childName: 'Sara Aslam',
        projectedScore: 95,
        focus: 'Science — Cell biology',
        confidence: 89,
      },
      {
        week: 'Aug 4 – Aug 10',
        childName: 'Ahmed Aslam',
        projectedScore: 93,
        focus: 'Board exam prep — mixed revision',
        confidence: 80,
      },
      {
        week: 'Aug 4 – Aug 10',
        childName: 'Sara Aslam',
        projectedScore: 96,
        focus: 'Science — Lab concepts',
        confidence: 86,
      },
    ],
  },
  settings: {
    emailAlerts: true,
    smsAlerts: false,
    sessionReminders: true,
    paymentAlerts: true,
    progressReports: true,
    weeklyDigest: true,
    profileVisible: true,
    shareProgressWithTutors: true,
    language: 'English',
    theme: 'light',
  },
};
