import { AlertTriangle, CheckCircle2, Clock, Zap } from 'lucide-react';
import type { AdminDashboardData } from '../../types/admin.types';
import { formatDateTime } from '../../utils/format';
import GlassCard from '../shared/GlassCard';
import StatCard from '../shared/StatCard';
import AiHealthWidget from '../widgets/AiHealthWidget';

interface AiSystemHealthPageProps {
  dashboard: AdminDashboardData;
}

const noteStatusStyles = {
  completed: 'bg-green-50 text-tl-green',
  failed: 'bg-red-50 text-tl-red',
  processing: 'bg-blue-50 text-tl-blue',
};

export default function AiSystemHealthPage({ dashboard }: AiSystemHealthPageProps) {
  const notes = dashboard.aiNotes ?? [];
  const health = dashboard.aiHealth;

  return (
    <>
      <section className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard
          title="Token Health"
          value={`${health.tokenHealth}%`}
          icon={Zap}
          accent="#7548F5"
          pulse={health.tokenHealth > 90}
        />
        <StatCard
          title="Avg Summary Speed"
          value={`${health.summarySpeedMs}ms`}
          icon={Clock}
          accent="#2E78F6"
        />
        <StatCard
          title="Notes Generated Today"
          value={String(health.notesGeneratedToday ?? 0)}
          icon={CheckCircle2}
          accent="#4AA570"
        />
        <StatCard
          title="Failed Summaries"
          value={String(health.failedSummaries ?? 0)}
          icon={AlertTriangle}
          accent="#EE6464"
          alert={(health.failedSummaries ?? 0) > 0}
        />
      </section>

      <div className="grid grid-cols-1 gap-6 xl:grid-cols-2">
        <AiHealthWidget health={health} />

        <GlassCard>
          <header className="border-b border-slate-100 px-5 py-4">
            <h2 className="text-lg font-bold text-tl-navy">
              Recent AI Note Logs
            </h2>
            <p className="text-sm text-slate-500">
              Session summaries generated by the AI engine
            </p>
          </header>
          <div className="max-h-[400px] overflow-y-auto">
            <table className="w-full text-left text-sm">
              <thead className="sticky top-0 bg-slate-50/90 text-xs font-semibold uppercase tracking-wide text-slate-500">
                <tr>
                  <th className="px-5 py-3">Session</th>
                  <th className="px-5 py-3">Subject</th>
                  <th className="px-5 py-3">Tokens</th>
                  <th className="px-5 py-3">Status</th>
                </tr>
              </thead>
              <tbody>
                {notes.map(note => (
                  <tr
                    key={note.id}
                    className="border-b border-slate-50 hover:bg-violet-50/20"
                  >
                    <td className="px-5 py-3">
                      <p className="font-medium text-tl-navy">
                        {note.tutorName}
                      </p>
                      <p className="text-xs text-slate-500">
                        with {note.studentName}
                      </p>
                      <p className="text-[10px] text-slate-400">
                        {formatDateTime(note.createdAt)}
                      </p>
                    </td>
                    <td className="px-5 py-3 text-slate-600">{note.subject}</td>
                    <td className="px-5 py-3">
                      <p className="font-semibold text-tl-navy">
                        {note.tokensUsed}
                      </p>
                      <p className="text-[10px] text-slate-400">
                        {note.durationMs}ms
                      </p>
                    </td>
                    <td className="px-5 py-3">
                      <span
                        className={`inline-flex rounded-full px-2 py-0.5 text-xs font-semibold capitalize ${noteStatusStyles[note.status]}`}
                      >
                        {note.status}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </GlassCard>
      </div>
    </>
  );
}
