import { StyleSheet } from "react-native";

export const createStyles = (colors: any, resp: any) =>
  StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: '#FFFFFF',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: resp.dx(20),
    },
    container: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    timerContainer: {
      position: 'relative',
      width: resp.dx(140),
      height: resp.dx(140),
      marginBottom: resp.dy(48),
      justifyContent: 'center',
      alignItems: 'center',
    },
    progressRingBg: {
      position: 'absolute',
      width: resp.dx(140),
      height: resp.dx(140),
      borderRadius: resp.dx(70),
      borderWidth: 4,
      borderColor: '#E5E7EB',
    },
    progressRing: {
      position: 'absolute',
      width: resp.dx(140),
      height: resp.dx(140),
      borderRadius: resp.dx(70),
      overflow: 'hidden',
    },
    progressSegment: {
      position: 'absolute',
      width: resp.dx(140),
      height: resp.dx(140),
      borderRadius: resp.dx(70),
      borderWidth: 4,
      borderColor: 'transparent',
      borderTopColor: '#10B981',
      borderRightColor: '#10B981',
    },
    checkmarkCircle: {
      width: resp.dx(96),
      height: resp.dx(96),
      borderRadius: resp.dx(48),
      backgroundColor: '#10B981',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#10B981',
      shadowOpacity: 0.3,
      shadowOffset: { width: 0, height: 8 },
      shadowRadius: 16,
      elevation: 12,
      zIndex: 10,
    },
    checkmarkIcon: {
      fontSize: resp.df(56),
      color: '#FFFFFF',
      fontWeight: '700',
    },
    countdownBadge: {
      position: 'absolute',
      bottom: resp.dy(-8),
      right: resp.dx(-8),
      width: resp.dx(48),
      height: resp.dx(48),
      borderRadius: resp.dx(24),
      backgroundColor: '#2563EB',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#2563EB',
      shadowOpacity: 0.3,
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 12,
      elevation: 8,
      zIndex: 20,
    },
    countdownText: {
      fontSize: resp.df(20),
      fontWeight: '700',
      color: '#FFFFFF',
    },
    titleText: {
      fontSize: resp.df(24),
      fontWeight: '700',
      color: '#111827',
      marginBottom: resp.dy(12),
      textAlign: 'center',
    },
    subtitleText: {
      fontSize: resp.df(14),
      color: '#4B5563',
      lineHeight: resp.df(22),
      textAlign: 'center',
      maxWidth: '85%',
    },
    boldText: {
      fontWeight: '700',
      color: '#2563EB',
    },
  });
